# Generated by Django 6.0.5 on 2026-05-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task_detail',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='New_Details', to='tasks.task'),
        ),
    ]
