# Generated by Django 6.0.5 on 2026-05-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_detail_notes_alter_task_detail_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_detail',
            name='assigned_to',
        ),
    ]
