# Generated by Django 6.0.5 on 2026-05-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_detail_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='New_Details', to='tasks.task'),
        ),
    ]
