# Generated by Django 6.0.5 on 2026-05-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_detail_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='New_Details', to='tasks.task'),
        ),
    ]
