# Generated by Django 6.0.5 on 2026-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_detail',
            name='asset',
            field=models.ImageField(blank=True, null=True, upload_to='task_asset'),
        ),
    ]
