# Generated by Django 6.0.5 on 2026-05-13 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='tasks.project'),
        ),
    ]
