# Generated by Django 6.0.5 on 2026-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_detail_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_detail',
            name='asset',
            field=models.ImageField(blank=True, default='task_asset/default.jpeg', null=True, upload_to='task_asset'),
        ),
    ]
